Repository plone/Products.Archetypes, pull requests merged in 2019-04, with the labels that each got.

#126 Fixed slowness in unicodeTestIn script used by keyword template.
  Products/Archetypes/skins/archetypes/unicodeTestIn.py
  Products/Archetypes/tests/test_widgets.py
  news/125.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review

#124 Make QueryStringWidgetTests more robust/independent of implementation details
  Products/Archetypes/tests/test_pawidgets.py
  news/124.bugfix
Labels: 04 type: enhancement, 23 status: testing

#128 Fixed slowness in unicodeTestIn script used by keyword template. [master]
  Products/Archetypes/skins/archetypes/unicodeTestIn.py
  Products/Archetypes/tests/test_widgets.py
  news/125.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing

#127 Fixed slowness in unicodeTestIn script used by keyword template. [1.15]
  Products/Archetypes/skins/archetypes/unicodeTestIn.py
  Products/Archetypes/tests/test_widgets.py
  news/125.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing

#129 Fixed UnicodeEncodeError when editing Archetypes rich text.
  Products/Archetypes/Widget.py
  news/2832.bugfix
Labels: 02 type: regression, 13 prio: normal, 23 status: testing, 32 needs: review
